services:
  web:
    build: ./ai_service/project
    container_name: ai_service-web
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./ai_service/project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./ai_service/project
    container_name: ai_service-worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./ai_service/project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  telegram_bot:
    build: ./telegram_bot/project
    container_name: telegram_bot
    environment:
      - API_URL=http://web:8000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - web

  redis:
    image: redis:7
    container_name: ai_service-redis
