export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS'
export const POST_INGREDIENT = 'POST_INGREDIENT'
export const POST_INGREDIENTS_RECIPE = 'POST_INGREDIENTS_RECIPE'
export const INIT_VALUE = 'INIT_VALUE'
