export const LOWER_LEVEL_DIFFICULTY_RECIPE='Lower'
export const MEDIUM_LEVEL_DIFFICULTY_RECIPE='Medium'
export const HIGH_LEVEL_DIFFICULTY_RECIPE='High'

export const COLOR_DEFAULT_TYPE_RECIPES='#5D87FF'